services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: pip
      POSTGRES_PASSWORD: pip
      POSTGRES_DB: pip
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
